sonar.organization=mkvlrn
sonar.projectKey=mkvlrn_template-node
sonar.language=ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sources=./src
sonar.exclusions=*.spec.ts,*.spec.tsx
sotar.tests=./src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.coverage.exclusions=**/*.spec.ts,**/*.spec.tsx,**/index.ts,**/index.tsx
