name: integration-e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"
      - run: yarn install
      - run: |
          yarn test:integration
          yarn test:e2e
